"""
add_new_exercises.py
Appends ~30 new exercises to assets/data/exercise_library.json to fill
movement-pattern coverage gaps (vertical_pull, elbow_extension,
shoulder_isolation, hip_isolation, etc.).

Skips: Incline Dumbbell Curl, Meadows Row, Hollow Body Hold (already exist).
"""

import json
import os

LIBRARY_PATH = os.path.join(
    os.path.dirname(__file__), "..", "assets", "data", "exercise_library.json"
)


def load_library(path: str) -> list:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save_library(path: str, data: list) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(data)} exercises to {path}")


def next_id(exercises: list) -> int:
    """Return the next sequential exercise number."""
    max_num = max(int(e["id"][1:]) for e in exercises)
    return max_num + 1


NEW_EXERCISES_TEMPLATE = [
    # ──────────────────────────────────────────────
    # LEGS — hip_isolation / hip_dominant / knee_dominant
    # ──────────────────────────────────────────────
    {
        "name": "Kas Glute Bridge",
        "category": "legs",
        "movement_pattern": "hip_isolation",
        "exercise_type": "isolation",
        "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hamstrings"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest_secs": 60,
        "tempo": "2-2-1-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale at the top, inhale on the descent",
        "coaching_cues": [
            "Keep toes raised off the floor to bias glutes over quads",
            "Push through the heel; squeeze hard at the top for 2 seconds",
            "Keep shins vertical; do NOT roll the pelvis — pure hip extension",
        ],
        "common_mistakes": [
            "Letting knees cave inward",
            "Using lower back instead of glutes at lockout",
            "Going too fast — tempo is critical here",
        ],
        "warmup_protocol": "1×20 bodyweight before weighted sets",
        "pro_tip": "Elevate upper back on a bench and add a barbell for the loaded version; the hip-extension ROM doubles",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["knee"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Glutes",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Hip Thrust",
        "priority_tier": 2,
    },
    {
        "name": "B-Stance RDL",
        "category": "legs",
        "movement_pattern": "hip_dominant",
        "exercise_type": "compound",
        "primary_muscles": ["Hamstrings", "Glutes"],
        "secondary_muscles": ["Erector Spinae"],
        "equipment_needed": ["Dumbbells"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_secs": 75,
        "tempo": "3-1-2-0",
        "met_value": 4.5,
        "cal_per_set_est": 9.0,
        "breathing_cue": "Inhale on the way down, exhale as you drive the hips",
        "coaching_cues": [
            "Front foot takes 90% of the load; back toe lightly touches for balance only",
            "Hinge at the hip — chest leads, hips go back",
            "Feel the stretch in the working hamstring at the bottom",
        ],
        "common_mistakes": [
            "Rounding the lower back",
            "Letting the back foot bear too much weight",
            "Squatting instead of hinging",
        ],
        "warmup_protocol": "1×10 per side BW Romanian hinge",
        "pro_tip": "Ideal for home training — a single DB in each hand gives unilateral hip-hinge stimulus without a barbell",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back"],
        "is_bilateral": False,
        "cns_demand": 3,
        "target_focus": "Hamstrings",
        "equipment_tier": ["home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Romanian Deadlift",
        "priority_tier": 2,
    },
    {
        "name": "Cable Pull-Through",
        "category": "legs",
        "movement_pattern": "hip_dominant",
        "exercise_type": "compound",
        "primary_muscles": ["Glutes", "Hamstrings"],
        "secondary_muscles": ["Erector Spinae"],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 4.0,
        "cal_per_set_est": 8.0,
        "breathing_cue": "Exhale forcefully as hips snap forward",
        "coaching_cues": [
            "Face away from the cable; rope between legs",
            "Hinge aggressively — push hips back until you feel hamstring stretch",
            "Drive hips through — think kettlebell swing, not squat",
        ],
        "common_mistakes": [
            "Squatting down instead of hinging back",
            "Using arm strength to pull — arms stay passive",
            "Hyperextending the lower back at lockout",
        ],
        "warmup_protocol": "2×10 very light, focus on hip-hinge pattern",
        "pro_tip": "Low cable = more glute; higher cable = more hamstring. Adjust for your weak point",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back"],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Glutes",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Romanian Deadlift",
        "priority_tier": 2,
    },
    {
        "name": "Hip Abductor Machine",
        "category": "legs",
        "movement_pattern": "hip_isolation",
        "exercise_type": "isolation",
        "primary_muscles": ["Glutes"],
        "secondary_muscles": ["Hip Abductors"],
        "equipment_needed": ["Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale on the push outward",
        "coaching_cues": [
            "Sit tall; keep core braced; avoid rocking the torso",
            "Full ROM — push as wide as the machine allows",
            "Controlled return — don't let the weights slam",
        ],
        "common_mistakes": [
            "Using momentum — slow and controlled every rep",
            "Tilting the torso to compensate for limited ROM",
            "Skipping the hold at full abduction",
        ],
        "warmup_protocol": "1×20 light before working sets",
        "pro_tip": "Finish with a 30-second isometric hold at full abduction — nasty glute burn and great for hypertrophy",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["hip"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Glutes",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Banded Lateral Walk",
        "priority_tier": 2,
    },
    {
        "name": "Frog Pumps",
        "category": "legs",
        "movement_pattern": "hip_isolation",
        "exercise_type": "isolation",
        "primary_muscles": ["Glutes"],
        "secondary_muscles": [],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "20-30",
        "default_rest_secs": 45,
        "tempo": "1-2-1-0",
        "met_value": 3.0,
        "cal_per_set_est": 4.0,
        "breathing_cue": "Continuous breathing; exhale at each peak contraction",
        "coaching_cues": [
            "Lie on back; soles of feet together, knees flared wide like a frog",
            "Drive hips straight up — the frog position externally rotates to hit the upper glute fibres",
            "Squeeze hard at the top; pause briefly before descending",
        ],
        "common_mistakes": [
            "Pushing feet apart instead of keeping soles together",
            "Using lower back — squeeze glutes before you lift",
            "Going too shallow on the hip extension",
        ],
        "warmup_protocol": "No warm-up needed; can be used as activation",
        "pro_tip": "Perfect glute activation drill before squats or deadlifts — 25 reps fires up the upper glute fibres that bridges miss",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["hip"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Glutes",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Kas Glute Bridge",
        "priority_tier": 3,
    },
    {
        "name": "High Box Step-Up",
        "category": "legs",
        "movement_pattern": "knee_dominant",
        "exercise_type": "compound",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "8-12",
        "default_rest_secs": 75,
        "tempo": "2-0-2-0",
        "met_value": 5.0,
        "cal_per_set_est": 9.0,
        "breathing_cue": "Exhale as you step up, inhale as you lower",
        "coaching_cues": [
            "Box height should have knee at ~90° when foot is planted — higher box = more glute",
            "Drive through the heel of the working leg; don't push off the back foot",
            "Stand fully tall at the top before stepping back down",
        ],
        "common_mistakes": [
            "Pushing off the trailing leg — defeats the purpose",
            "Box too low — becomes more of a lunge than a step-up",
            "Knee caving inward on the drive up",
        ],
        "warmup_protocol": "1×10 BW each side on lower box",
        "pro_tip": "Hold dumbbells at sides to load without needing a barbell; works equally well at home with a sturdy chair or steps",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["knee"],
        "is_bilateral": False,
        "cns_demand": 2,
        "target_focus": "Quads",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Bulgarian Split Squat",
        "priority_tier": 2,
    },
    {
        "name": "Deficit Reverse Lunge",
        "category": "legs",
        "movement_pattern": "knee_dominant",
        "exercise_type": "compound",
        "primary_muscles": ["Quads", "Glutes"],
        "secondary_muscles": ["Hamstrings", "Core"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_secs": 75,
        "tempo": "3-0-2-0",
        "met_value": 4.5,
        "cal_per_set_est": 8.0,
        "breathing_cue": "Inhale as you step back and lower, exhale as you drive up",
        "coaching_cues": [
            "Stand on a 2-4 inch platform to increase ROM at the bottom",
            "Step back far enough for the knee to nearly touch the floor",
            "Keep torso upright — resist the urge to lean forward",
        ],
        "common_mistakes": [
            "Step too short — front knee travels excessively over the toe",
            "Allowing torso to fold forward under load",
            "Rushing the eccentric — slow the descent to 3 seconds",
        ],
        "warmup_protocol": "1×10 BW reverse lunges without deficit",
        "pro_tip": "Add a slight forward lean (10°) if your goal is glute development; stay upright for quad dominance",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["knee"],
        "is_bilateral": False,
        "cns_demand": 2,
        "target_focus": "Quads",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Reverse Lunge",
        "priority_tier": 2,
    },
    {
        "name": "Stiff-Legged Deadlift",
        "category": "legs",
        "movement_pattern": "hip_dominant",
        "exercise_type": "compound",
        "primary_muscles": ["Hamstrings"],
        "secondary_muscles": ["Glutes", "Erector Spinae"],
        "equipment_needed": ["Barbell"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 4,
        "default_reps": "8-10",
        "default_rest_secs": 90,
        "tempo": "3-1-2-0",
        "met_value": 5.0,
        "cal_per_set_est": 10.0,
        "breathing_cue": "Inhale and brace at the top, exhale after lockout",
        "coaching_cues": [
            "Keep legs almost fully extended — slight soft bend at knee, NOT bent",
            "Bar travels down the shins; hinge until you feel max hamstring stretch",
            "Drive hips forward to return; squeeze glutes hard at lockout",
        ],
        "common_mistakes": [
            "Rounding the lower back — brace the core hard throughout",
            "Bending the knees into a regular deadlift position",
            "Bar drifting forward away from the body",
        ],
        "warmup_protocol": "2×10 at 50% with focus on hamstring stretch",
        "pro_tip": "Elevate the bar 1-2 inches on plates if hamstring flexibility limits depth — safer than rounding",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back", "hamstring"],
        "is_bilateral": True,
        "cns_demand": 3,
        "target_focus": "Hamstrings",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Romanian Deadlift",
        "priority_tier": 2,
    },
    {
        "name": "Standing Single Leg Curl",
        "category": "legs",
        "movement_pattern": "hip_dominant",
        "exercise_type": "isolation",
        "primary_muscles": ["Hamstrings"],
        "secondary_muscles": [],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale as you curl the heel toward your glute",
        "coaching_cues": [
            "Attach ankle strap to low cable; stand facing the stack",
            "Keep the working knee aligned with the standing knee — don't flare it",
            "Control the extension; don't let the weight snap the leg straight",
        ],
        "common_mistakes": [
            "Swinging the hip to complete the rep",
            "Not fully extending the leg on the eccentric",
            "Using too much weight — hamstrings are strong, but isolation requires control",
        ],
        "warmup_protocol": "1×15 very light for joint warm-up",
        "pro_tip": "Single-leg version addresses side-to-side hamstring imbalances that prone leg curl misses; great rehab and prehab tool",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["hamstring"],
        "is_bilateral": False,
        "cns_demand": 1,
        "target_focus": "Hamstrings",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Prone Leg Curl",
        "priority_tier": 2,
    },
    # ──────────────────────────────────────────────
    # CHEST — horizontal_push
    # ──────────────────────────────────────────────
    {
        "name": "Decline Dumbbell Press",
        "category": "push",
        "movement_pattern": "horizontal_push",
        "exercise_type": "compound",
        "primary_muscles": ["Lower Chest"],
        "secondary_muscles": ["Triceps", "Front Deltoid"],
        "equipment_needed": ["Dumbbells", "Decline Bench"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_secs": 90,
        "tempo": "3-1-2-0",
        "met_value": 4.5,
        "cal_per_set_est": 9.0,
        "breathing_cue": "Inhale on the descent, exhale on the press",
        "coaching_cues": [
            "Set feet securely on the pad; 15-30° decline angle",
            "DBs at chest level, not shoulders — the decline already shifts the vector",
            "Press to full extension but don't lose chest tension at lockout",
        ],
        "common_mistakes": [
            "Excessive decline — over 45° causes shoulder discomfort",
            "Letting DBs drift toward the head",
            "Rushing the eccentric phase",
        ],
        "warmup_protocol": "2×12 at 60% with lighter DBs",
        "pro_tip": "Decline angle shifts the peak-contraction point lower on the chest — better lower-pec stretch than flat bench",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": True,
        "cns_demand": 3,
        "target_focus": "Lower Chest",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Dumbbell Bench Press",
        "priority_tier": 2,
    },
    {
        "name": "Incline Dumbbell Fly",
        "category": "push",
        "movement_pattern": "horizontal_push",
        "exercise_type": "isolation",
        "primary_muscles": ["Upper Chest"],
        "secondary_muscles": ["Front Deltoid"],
        "equipment_needed": ["Dumbbells", "Incline Bench"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "3-1-2-0",
        "met_value": 4.0,
        "cal_per_set_est": 7.0,
        "breathing_cue": "Inhale as arms open, exhale as they come together",
        "coaching_cues": [
            "Slight permanent bend in the elbow — DO NOT straighten arms",
            "Open wide enough for a strong pec stretch; stop before shoulder discomfort",
            "Think 'hugging a barrel' — arc motion, not a pressing motion",
        ],
        "common_mistakes": [
            "Straightening elbows — converts fly to press, removes pec stretch",
            "Going too heavy — the fly is a stretch exercise, not a strength move",
            "Bouncing at the bottom — high injury risk",
        ],
        "warmup_protocol": "1×15 very light for shoulder mobility",
        "pro_tip": "Use as a pre-exhaustion move before incline press — the pump will be intense",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Upper Chest",
        "equipment_tier": ["home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Cable Fly",
        "priority_tier": 2,
    },
    {
        "name": "Deficit Push-Up",
        "category": "push",
        "movement_pattern": "horizontal_push",
        "exercise_type": "compound",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Triceps", "Front Deltoid"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-15",
        "default_rest_secs": 75,
        "tempo": "3-2-1-0",
        "met_value": 4.5,
        "cal_per_set_est": 7.0,
        "breathing_cue": "Inhale on the way down to full depth, exhale on the push",
        "coaching_cues": [
            "Hands on push-up handles, books, or parallettes — feet on a flat surface",
            "Lower until chest is well below hand level for maximum pec stretch",
            "Elbows at 45° — not flared wide, not tucked tight",
        ],
        "common_mistakes": [
            "Hands too close together — reduces chest ROM",
            "Sagging hips — maintain a rigid plank from head to heel",
            "Bouncing at the bottom of the stretch",
        ],
        "warmup_protocol": "1×10 standard push-ups before deficit version",
        "pro_tip": "The extra few centimetres of ROM at the bottom are where the majority of the hypertrophy stimulus lives — this is a bodyweight DB fly equivalent",
        "is_indian_context": False,
        "indian_alternative": "Use two thick books or stacked water bottles as handles",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder", "wrist"],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Mid Chest",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Push-Up",
        "priority_tier": 2,
    },
    {
        "name": "Floor Press",
        "category": "push",
        "movement_pattern": "horizontal_push",
        "exercise_type": "compound",
        "primary_muscles": ["Chest"],
        "secondary_muscles": ["Triceps", "Front Deltoid"],
        "equipment_needed": ["Dumbbells"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_secs": 90,
        "tempo": "3-2-1-0",
        "met_value": 4.5,
        "cal_per_set_est": 9.0,
        "breathing_cue": "Inhale on the descent, exhale on the press",
        "coaching_cues": [
            "Lie on the floor; upper arms rest on the floor at the bottom of each rep",
            "Elbows stop at floor — never bounce; pause 1 second before pressing",
            "Excellent for shoulder safety — limited ROM removes the risky stretched position",
        ],
        "common_mistakes": [
            "Letting elbows slam to the floor rather than softly touching",
            "Arching the lower back excessively off the floor",
            "Using bench-press grip width — go slightly narrower for floor press",
        ],
        "warmup_protocol": "2×10 at 60% working weight",
        "pro_tip": "Floor press is the best home-gym chest exercise with no bench — perfect tricep and chest strength builder that spares the shoulder",
        "is_indian_context": True,
        "indian_alternative": "No bench required — the floor is the bench",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": [],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Mid Chest",
        "equipment_tier": ["home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Dumbbell Bench Press",
        "priority_tier": 2,
    },
    # ──────────────────────────────────────────────
    # SHOULDERS — shoulder_isolation / vertical_push
    # ──────────────────────────────────────────────
    {
        "name": "Machine Lateral Raise",
        "category": "push",
        "movement_pattern": "shoulder_isolation",
        "exercise_type": "isolation",
        "primary_muscles": ["Lateral Delts"],
        "secondary_muscles": [],
        "equipment_needed": ["Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 4,
        "default_reps": "15-20",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale on the lift, inhale on the controlled lower",
        "coaching_cues": [
            "Set the arm pad just below the elbow — not on the wrist",
            "Slight forward lean on the machine targets the lateral delt more precisely",
            "Lead with the elbow, not the wrist — think 'push elbow up to the ceiling'",
        ],
        "common_mistakes": [
            "Going too heavy and shrugging — trap dominance will mask delt work",
            "Not reaching full lateral height — 90° or slightly above",
            "Jerking the weight up with momentum",
        ],
        "warmup_protocol": "1×20 very light to warm up the rotator cuff",
        "pro_tip": "Machine allows constant tension through the full arc — superior to dumbbell for lateral delt isolation at high reps",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Lateral Delts",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Dumbbell Lateral Raise",
        "priority_tier": 2,
    },
    {
        "name": "Cable Front Raise",
        "category": "push",
        "movement_pattern": "shoulder_isolation",
        "exercise_type": "isolation",
        "primary_muscles": ["Front Delts"],
        "secondary_muscles": ["Lateral Delts"],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale as you raise your arm, inhale as you lower",
        "coaching_cues": [
            "Attach a bar or handle to a low cable; stand facing away",
            "Raise arm to shoulder height — going higher increases trap and neck recruitment",
            "Slight elbow bend; keep the arm aligned with the front delt angle (30° off sagittal)",
        ],
        "common_mistakes": [
            "Swinging the torso to initiate the raise",
            "Raising beyond 90° — diminishing returns and higher impingement risk",
            "Letting the weight pull the arm straight back — control the eccentric",
        ],
        "warmup_protocol": "1×15 very light",
        "pro_tip": "Cable version keeps tension on the front delt at the bottom — dumbbell version doesn't. Better for the lengthened-position stimulus",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": False,
        "cns_demand": 1,
        "target_focus": "Front Delts",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Dumbbell Front Raise",
        "priority_tier": 3,
    },
    {
        "name": "Egyptian Lateral Raise",
        "category": "push",
        "movement_pattern": "shoulder_isolation",
        "exercise_type": "isolation",
        "primary_muscles": ["Lateral Delts"],
        "secondary_muscles": [],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-3-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale on the raise, slow exhale on the 3-second lower",
        "coaching_cues": [
            "Stand sideways to a low cable; hold a fixed support with the other hand and lean away",
            "The tilt increases the ROM in the lengthened position — peak stretch at the bottom",
            "Raise the arm in the scapular plane (30° forward) — not directly sideways",
        ],
        "common_mistakes": [
            "Not leaning far enough — the lean is what makes the lengthened-position superior",
            "Going too fast on the eccentric — the slow lower is where the growth signal lives",
            "Arm drifting in front of the body — stay in the scapular plane",
        ],
        "warmup_protocol": "1×15 standard cable lateral raise before attempting",
        "pro_tip": "The research-backed 'best' lateral raise variant — lengthened-position tension is 2× more hypertrophic than dumbbell laterals for the same reps",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": False,
        "cns_demand": 2,
        "target_focus": "Lateral Delts",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Dumbbell Lateral Raise",
        "priority_tier": 2,
    },
    # ──────────────────────────────────────────────
    # TRICEPS — elbow_extension
    # ──────────────────────────────────────────────
    {
        "name": "Bench Dips",
        "category": "push",
        "movement_pattern": "elbow_extension",
        "exercise_type": "compound",
        "primary_muscles": ["Triceps"],
        "secondary_muscles": ["Front Deltoid", "Chest"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "3-0-2-0",
        "met_value": 4.0,
        "cal_per_set_est": 6.0,
        "breathing_cue": "Inhale on the dip down, exhale on the press up",
        "coaching_cues": [
            "Hands shoulder-width on the bench edge; hips close to the bench",
            "Elbows point backward — not flared — to keep tension on the triceps",
            "Lower until upper arm is parallel to the floor; don't go below 90° shoulder",
        ],
        "common_mistakes": [
            "Dipping too deep — causes shoulder impingement",
            "Elbows flaring sideways — shifts load off triceps",
            "Hips drifting far out — increases shoulder stress",
        ],
        "warmup_protocol": "1×10 very light at shallow depth",
        "pro_tip": "Elevate feet on another bench to increase loading; add a plate on the thighs for extra resistance — great bodyweight tricep builder",
        "is_indian_context": True,
        "indian_alternative": "Use a sturdy chair or low wall",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Triceps",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Tricep Dips",
        "priority_tier": 2,
    },
    {
        "name": "Dumbbell Kickback",
        "category": "push",
        "movement_pattern": "elbow_extension",
        "exercise_type": "isolation",
        "primary_muscles": ["Triceps"],
        "secondary_muscles": [],
        "equipment_needed": ["Dumbbells"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale as you extend the arm back fully",
        "coaching_cues": [
            "Upper arm locked parallel to the floor and torso — ONLY the forearm moves",
            "Extend fully — the tricep contracts hardest in the extended-arm position",
            "Hinge forward 45-60° and brace the core to protect the lower back",
        ],
        "common_mistakes": [
            "Upper arm dropping — loses tension on the tricep entirely",
            "Swinging the weight with shoulder momentum",
            "Not achieving full elbow extension — partial reps underutilise the long head",
        ],
        "warmup_protocol": "1×15 very light to warm up the elbow joint",
        "pro_tip": "Supinate (rotate palm up) at full extension for a harder tricep contraction — a 10% strength boost for free",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["elbow"],
        "is_bilateral": False,
        "cns_demand": 1,
        "target_focus": "Triceps",
        "equipment_tier": ["home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Tricep Pushdown",
        "priority_tier": 2,
    },
    {
        "name": "Overhead Cable Extension",
        "category": "push",
        "movement_pattern": "elbow_extension",
        "exercise_type": "isolation",
        "primary_muscles": ["Triceps (Long Head)"],
        "secondary_muscles": [],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "3-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Inhale on the stretch overhead, exhale on extension",
        "coaching_cues": [
            "Face away from the stack; grab rope overhead with both hands behind the head",
            "Keep elbows pointing directly upward — don't let them flare outward",
            "Full extension above the head; feel the long head stretch at the bottom",
        ],
        "common_mistakes": [
            "Elbows flaring out wide — removes long-head focus",
            "Arching the lower back — engage core tightly",
            "Using too much weight and sacrificing the stretch at the bottom",
        ],
        "warmup_protocol": "1×15 very light to warm up elbow and shoulder",
        "pro_tip": "The overhead position maximally stretches the long head of the tricep — 30% more growth stimulus than pushdowns for the same reps according to recent research",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["elbow", "shoulder"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Triceps (Long Head)",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Overhead Dumbbell Extension",
        "priority_tier": 2,
    },
    {
        "name": "Close-Grip Bench Press",
        "category": "push",
        "movement_pattern": "elbow_extension",
        "exercise_type": "compound",
        "primary_muscles": ["Triceps"],
        "secondary_muscles": ["Chest", "Front Deltoid"],
        "equipment_needed": ["Barbell", "Bench"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 4,
        "default_reps": "8-12",
        "default_rest_secs": 90,
        "tempo": "3-1-2-0",
        "met_value": 4.8,
        "cal_per_set_est": 9.0,
        "breathing_cue": "Inhale on the descent, exhale hard on the press",
        "coaching_cues": [
            "Grip just inside shoulder width — narrower than bench press but NOT touching",
            "Elbows track close to the torso; elbow angle 20-30° from the body",
            "Bar touches lower chest — NOT the same touch point as bench press",
        ],
        "common_mistakes": [
            "Grip too narrow — wrist strain and reduced force output",
            "Elbows flaring wide — converts to a chest exercise",
            "Partial reps at the top — full lockout is where tricep finishes the rep",
        ],
        "warmup_protocol": "2×10 at 50% working weight",
        "pro_tip": "One of the best strength builders for the tricep — can carry over 10-15kg to regular bench press by fixing a tricep-weak lockout",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder", "wrist"],
        "is_bilateral": True,
        "cns_demand": 3,
        "target_focus": "Triceps",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Tricep Dips",
        "priority_tier": 2,
    },
    # ──────────────────────────────────────────────
    # BICEPS — elbow_flexion
    # ──────────────────────────────────────────────
    {
        "name": "Rope Hammer Curl",
        "category": "pull",
        "movement_pattern": "elbow_flexion",
        "exercise_type": "isolation",
        "primary_muscles": ["Biceps", "Brachialis"],
        "secondary_muscles": ["Brachioradialis"],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.0,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale as you curl up",
        "coaching_cues": [
            "Neutral (thumbs-up) grip throughout — do NOT supinate",
            "Elbows pinned to sides; only the forearm moves",
            "Squeeze hard at the top; control the cable on the way down",
        ],
        "common_mistakes": [
            "Supinating at the top — that would make it a standard curl, not hammer",
            "Elbows drifting forward — loses brachialis tension",
            "Too much wrist flexion at the top",
        ],
        "warmup_protocol": "1×15 very light",
        "pro_tip": "The brachialis lies under the bicep — building it pushes the bicep peak up. Rope hammers are the most efficient way to isolate it",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["elbow"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Biceps/Brachialis",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Hammer Curl",
        "priority_tier": 2,
    },
    {
        "name": "High Cable Curl",
        "category": "pull",
        "movement_pattern": "elbow_flexion",
        "exercise_type": "isolation",
        "primary_muscles": ["Biceps"],
        "secondary_muscles": [],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.0,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale as you flex the bicep toward your ear",
        "coaching_cues": [
            "Set cables at head height; face the cable stack; curl toward your ears",
            "Upper arm stays parallel to the floor — elbows fixed in space",
            "Feel the bicep stretch at the start (arm extended forward) and squeeze at peak contraction",
        ],
        "common_mistakes": [
            "Elbow dropping below head height — loses the lengthened-position advantage",
            "Using both arms asymmetrically — if using two cables, keep motion symmetrical",
            "Jerking the curl — smooth constant tension is the goal",
        ],
        "warmup_protocol": "1×15 very light",
        "pro_tip": "High-cable curl is the lengthened-position bicep exercise — the stretch under load is where hypertrophy research says growth is maximised",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["elbow"],
        "is_bilateral": False,
        "cns_demand": 1,
        "target_focus": "Biceps",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Barbell Curl",
        "priority_tier": 2,
    },
    # ──────────────────────────────────────────────
    # BACK — vertical_pull / horizontal_pull
    # ──────────────────────────────────────────────
    {
        "name": "Pendlay Row",
        "category": "pull",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "compound",
        "primary_muscles": ["Lats (Thickness)", "Mid Back"],
        "secondary_muscles": ["Biceps", "Rear Delts", "Erector Spinae"],
        "equipment_needed": ["Barbell"],
        "logging_type": "weight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 4,
        "default_reps": "5-8",
        "default_rest_secs": 120,
        "tempo": "X-1-2-0",
        "met_value": 5.5,
        "cal_per_set_est": 11.0,
        "breathing_cue": "Inhale and brace before each rep; exhale after each rep reset",
        "coaching_cues": [
            "Bar starts on the floor each rep — true dead-stop row (no bounce)",
            "Torso nearly horizontal (10-20° above parallel) at the start",
            "Explosive pull to lower chest; bar path is nearly vertical",
        ],
        "common_mistakes": [
            "Torso angle too upright — becomes a partial barbell row, not a Pendlay",
            "Not resetting to the floor each rep — removes the strict dead-stop stimulus",
            "Lower back rounding — brace hard before every pull",
        ],
        "warmup_protocol": "2×8 at 50% working weight",
        "pro_tip": "The dead-stop teaches pure hip-hinge and back strength with zero momentum — 5 kg more on Pendlay Row adds 10 kg to your deadlift over a training cycle",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back"],
        "is_bilateral": True,
        "cns_demand": 4,
        "target_focus": "Lats (Thickness)",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Barbell Row",
        "priority_tier": 2,
    },
    {
        "name": "Machine High Row",
        "category": "pull",
        "movement_pattern": "vertical_pull",
        "exercise_type": "compound",
        "primary_muscles": ["Lats (Width)"],
        "secondary_muscles": ["Biceps", "Rear Delts"],
        "equipment_needed": ["Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_secs": 75,
        "tempo": "2-1-3-0",
        "met_value": 4.5,
        "cal_per_set_est": 8.0,
        "breathing_cue": "Exhale as you pull down, inhale as arms extend overhead",
        "coaching_cues": [
            "Chest pad supports the torso; pull handles down toward the upper chest",
            "Lead with the elbows; think 'elbows to pockets' — not hands to chest",
            "Full stretch at the top — let the lats lengthen completely before each rep",
        ],
        "common_mistakes": [
            "Pulling with biceps instead of driving elbows down",
            "Not getting full overhead stretch — the lengthened position matters most",
            "Leaning back excessively — keep chest on the pad",
        ],
        "warmup_protocol": "1×15 light to prime lat-bicep connection",
        "pro_tip": "The chest-supported position removes lower back from the equation — great for high-volume lat work when the lower back is fatigued from deadlifts",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": [],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Lats (Width)",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Lat Pulldown",
        "priority_tier": 2,
    },
    {
        "name": "Machine Low Row",
        "category": "pull",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "compound",
        "primary_muscles": ["Mid Back (Thickness)"],
        "secondary_muscles": ["Biceps", "Lats", "Rear Delts"],
        "equipment_needed": ["Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest_secs": 75,
        "tempo": "2-1-2-0",
        "met_value": 4.5,
        "cal_per_set_est": 8.0,
        "breathing_cue": "Exhale as you row, inhale as you extend",
        "coaching_cues": [
            "Chest on pad; pull handles toward the lower abdomen, elbows close to the body",
            "Retract scapulae at the back of the movement — squeeze shoulder blades together",
            "Controlled full stretch forward — don't lose the mid-back tension",
        ],
        "common_mistakes": [
            "Shrugging the traps instead of retracting the scapulae",
            "Bouncing out of the stretched position — slow, controlled eccentric",
            "Pulling too high — row to navel, not to chest",
        ],
        "warmup_protocol": "1×15 light for shoulder and mid-back activation",
        "pro_tip": "Closer neutral grip hits the mid-back rhomboids and traps harder; wider pronated grip shifts emphasis to the lats. Use both across your training week",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": [],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Mid Back (Thickness)",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Cable Seated Row",
        "priority_tier": 2,
    },
    {
        "name": "Straight-Arm Pulldown",
        "category": "pull",
        "movement_pattern": "vertical_pull",
        "exercise_type": "isolation",
        "primary_muscles": ["Lats"],
        "secondary_muscles": ["Teres Major", "Core"],
        "equipment_needed": ["Cable Machine"],
        "logging_type": "weight_reps",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 6.0,
        "breathing_cue": "Exhale as you push the bar down toward your thighs",
        "coaching_cues": [
            "Arms stay straight the ENTIRE movement — this is NOT a lat pulldown",
            "Hinge slightly at the hips; pull the bar in a sweeping arc from overhead to thighs",
            "Think 'armpits to pockets' — this movement is pure lat without bicep interference",
        ],
        "common_mistakes": [
            "Bending the elbows — converts to a lat pulldown and removes the isolation",
            "Using too much weight and swinging the torso",
            "Not reaching full overhead stretch at the start",
        ],
        "warmup_protocol": "1×15 very light to feel the lat-shoulder connection",
        "pro_tip": "Best pure lat isolation exercise — zero bicep involvement. If you want to feel your lats without bicep fatigue, this is it",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": True,
        "cns_demand": 2,
        "target_focus": "Lats",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Lat Pulldown",
        "priority_tier": 2,
    },
    # ──────────────────────────────────────────────
    # CORE
    # ──────────────────────────────────────────────
    {
        "name": "Captain's Chair Leg Raise",
        "category": "core",
        "movement_pattern": "core",
        "exercise_type": "isolation",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "equipment_needed": ["Machine"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "2-1-2-0",
        "met_value": 3.5,
        "cal_per_set_est": 6.0,
        "breathing_cue": "Exhale as you raise the legs, inhale on the lower",
        "coaching_cues": [
            "Back flat against the pad; arms pressing down into the supports",
            "Posterior pelvic tilt — tuck the pelvis BEFORE lifting; this switches hip flexors off",
            "Raise knees to 90° for beginner; straight-leg raise for advanced",
        ],
        "common_mistakes": [
            "Swinging the legs with momentum — slow controlled reps only",
            "Not tilting the pelvis — most of the work goes to hip flexors instead of abs",
            "Lower back arching away from the pad",
        ],
        "warmup_protocol": "1×10 knee raises before straight-leg version",
        "pro_tip": "Add a twist at the top to target obliques — brings knee toward the opposite elbow at peak contraction",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back", "hip"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Core",
        "equipment_tier": ["basic_gym", "full_gym"],
        "standard_swap": "Hanging Leg Raise",
        "priority_tier": 2,
    },
    {
        "name": "V-Ups",
        "category": "core",
        "movement_pattern": "core",
        "exercise_type": "isolation",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "bodyweight_reps",
        "difficulty_level": "intermediate",
        "suitable_for": ["Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest_secs": 60,
        "tempo": "1-1-1-0",
        "met_value": 3.5,
        "cal_per_set_est": 5.0,
        "breathing_cue": "Exhale sharply as you fold up into the V position",
        "coaching_cues": [
            "Start lying flat; simultaneously raise straight legs and straight arms to meet",
            "Reach fingers toward toes at the peak; spine should form a deep C-curve",
            "Control the return — do NOT slam back to the floor",
        ],
        "common_mistakes": [
            "Bending the knees — makes the exercise significantly easier, removes load",
            "Using momentum to swing up rather than a controlled abdominal crunch",
            "Dropping back fast — the eccentric is where abdominal strength is built",
        ],
        "warmup_protocol": "1×10 regular crunches to activate abs first",
        "pro_tip": "Harder than it looks — if lower back arches or you cannot keep legs straight, regress to tuck V-ups first",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Core",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Sit-Up",
        "priority_tier": 2,
    },
    {
        "name": "Flutter Kicks",
        "category": "core",
        "movement_pattern": "core",
        "exercise_type": "isolation",
        "primary_muscles": ["Core"],
        "secondary_muscles": ["Hip Flexors"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "timed",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "30s",
        "default_rest_secs": 45,
        "tempo": "",
        "met_value": 3.5,
        "cal_per_set_est": 4.0,
        "breathing_cue": "Breathe steadily throughout; exhale every few kicks",
        "coaching_cues": [
            "Lie on back; lift both feet 6 inches off the floor",
            "Alternate small quick kicks; lower back pressed firmly to the floor throughout",
            "Point toes to keep tension on the core and hip flexors",
        ],
        "common_mistakes": [
            "Lower back arching off the floor — reduces core demand and risks injury",
            "Lifting feet too high — makes it easier; stay low at 6 inches",
            "Holding the breath — breathe rhythmically",
        ],
        "warmup_protocol": "Not required; can be used as active warm-up",
        "pro_tip": "Lower Abs Superset: flutter kicks 30s → leg raise 10 reps → rest 60s. Devastating lower-abdominal burnout circuit",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["lower_back"],
        "is_bilateral": True,
        "cns_demand": 1,
        "target_focus": "Core",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Plank",
        "priority_tier": 2,
    },
    {
        "name": "Side Plank",
        "category": "core",
        "movement_pattern": "core",
        "exercise_type": "isolation",
        "primary_muscles": ["Core", "Obliques"],
        "secondary_muscles": ["Glutes", "Hip Abductors"],
        "equipment_needed": ["Bodyweight"],
        "logging_type": "timed",
        "difficulty_level": "beginner",
        "suitable_for": ["Beginner", "Intermediate", "Advanced"],
        "default_sets": 3,
        "default_reps": "30s",
        "default_rest_secs": 45,
        "tempo": "",
        "met_value": 3.0,
        "cal_per_set_est": 3.0,
        "breathing_cue": "Breathe slowly and steadily throughout the hold",
        "coaching_cues": [
            "Elbow directly below the shoulder; body forms a straight diagonal line",
            "Lift the hips high — do NOT sag; squeeze the oblique to keep the position",
            "Stack feet or stagger them for stability; raise the top arm for extra challenge",
        ],
        "common_mistakes": [
            "Hips sagging below the line — defeats the purpose",
            "Neck craning upward — keep it neutral, in line with the spine",
            "Elbow placed too far from under the shoulder — makes it unstable",
        ],
        "warmup_protocol": "Not required; great as an activation drill",
        "pro_tip": "Add a hip dip (controlled tap to the floor and back up) to make it dynamic — transforms a static hold into a loaded oblique movement",
        "is_indian_context": False,
        "indian_alternative": "",
        "source": "Exercise science",
        "is_active": True,
        "is_foundational": False,
        "injury_contraindications": ["shoulder"],
        "is_bilateral": False,
        "cns_demand": 1,
        "target_focus": "Core/Obliques",
        "equipment_tier": ["bodyweight", "home_dumbbells", "basic_gym", "full_gym"],
        "standard_swap": "Plank",
        "priority_tier": 2,
    },
]


def build_exercises(exercises: list, start_id: int) -> list:
    """Assign sequential IDs and set defaults for optional fields."""
    result = []
    for i, ex in enumerate(exercises):
        ex["id"] = f"E{start_id + i:03d}"
        # Ensure fields that appeared in some but not all existing exercises are present
        ex.setdefault("is_foundational", False)
        ex.setdefault("is_active", True)
        ex.setdefault("source", "Exercise science")
        result.append(ex)
    return result


def main():
    library = load_library(LIBRARY_PATH)
    existing_names = {e["name"] for e in library}

    start_id = next_id(library)
    print(f"Current count: {len(library)}, next ID: E{start_id:03d}")

    new_exercises = build_exercises(NEW_EXERCISES_TEMPLATE, start_id)

    added = 0
    skipped = 0
    for ex in new_exercises:
        if ex["name"] in existing_names:
            print(f"  SKIP (duplicate): {ex['name']}")
            skipped += 1
        else:
            library.append(ex)
            existing_names.add(ex["name"])
            added += 1
            # Update id to be sequential based on actual position
    # Re-number added exercises to fill any gaps from skipped duplicates
    # (already assigned above, but gaps may exist — reassign to keep IDs sequential)
    base = start_id
    for ex in library[-(added):]:
        ex["id"] = f"E{base:03d}"
        base += 1

    print(f"Added: {added}, Skipped (already exist): {skipped}")
    save_library(LIBRARY_PATH, library)


if __name__ == "__main__":
    main()
