// Builds docs/adr/INDEX.md from the set of NNNN-<slug>.md files in docs/adr/.
//
// Usage:
//   dart run scripts/build_adr_index.dart
//
// Output: docs/adr/INDEX.md with a sorted table:
//   | ID | Title | Status | Date |
//
// Idempotent: re-runs produce identical output (unless an ADR was added or modified).

import 'dart:io';

void main() {
  final dir = Directory('docs/adr');
  if (!dir.existsSync()) {
    stderr.writeln('docs/adr/ does not exist');
    exit(1);
  }

  final rows = <List<String>>[];

  final files = dir
      .listSync()
      .whereType<File>()
      .where((f) =>
          f.path.endsWith('.md') &&
          !f.path.endsWith('INDEX.md') &&
          !f.path.endsWith('README.md'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final f in files) {
    final content = f.readAsStringSync().replaceAll('\r\n', '\n');
    final fm = _parseFrontmatter(content);
    if (fm == null) continue;
    final filename = f.path.replaceAll('\\', '/').split('/').last;
    final id = fm['adr_id'] ?? '????';
    final title = fm['title'] ?? '(no title)';
    final status = fm['status'] ?? '(no status)';
    final date = fm['date'] ?? '????-??-??';
    rows.add([
      'ADR-${id.padLeft(4, '0')}',
      '[$title]($filename)',
      status,
      date,
    ]);
  }

  final buf = StringBuffer();
  buf.writeln('# ADR Index');
  buf.writeln();
  buf.writeln('Auto-generated by `scripts/build_adr_index.dart`. '
      'Do not edit by hand.');
  buf.writeln();
  buf.writeln('Total: ${rows.length} ADR(s).');
  buf.writeln();
  buf.writeln('| ID | Title | Status | Date |');
  buf.writeln('|---|---|---|---|');
  for (final r in rows) {
    buf.writeln('| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} |');
  }
  buf.writeln();
  buf.writeln('See [README.md](README.md) for the ADR convention + how to '
      'add a new ADR (use `/adr`).');

  File('docs/adr/INDEX.md').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote docs/adr/INDEX.md (${rows.length} entries).');
}

Map<String, String>? _parseFrontmatter(String content) {
  if (!content.startsWith('---\n')) return null;
  final end = content.indexOf('\n---\n', 4);
  if (end == -1) return null;
  final block = content.substring(4, end);
  final fm = <String, String>{};
  for (final line in block.split('\n')) {
    final m = RegExp(r'^([a-z_]+)\s*:\s*(.+)$').firstMatch(line);
    if (m != null) fm[m.group(1)!] = m.group(2)!.trim();
  }
  return fm;
}
