// Builds docs/incidents/INDEX.md from docs/incidents/<date>-<slug>-<id>.md files.
//
// Sorts by detected_at descending (newest first).
//
// Usage:
//   dart run scripts/build_incident_index.dart

import 'dart:io';

void main() {
  final dir = Directory('docs/incidents');
  if (!dir.existsSync()) {
    stderr.writeln('docs/incidents/ does not exist');
    exit(1);
  }

  final rows = <List<String>>[];

  final files = dir
      .listSync()
      .whereType<File>()
      .where((f) =>
          f.path.endsWith('.md') &&
          !f.path.endsWith('INDEX.md') &&
          !f.path.endsWith('_template.md'))
      .toList()
    ..sort((a, b) => b.path.compareTo(a.path));

  for (final f in files) {
    final content = f.readAsStringSync().replaceAll('\r\n', '\n');
    final fm = _parseFrontmatter(content);
    if (fm == null) continue;
    final filename = f.path.replaceAll('\\', '/').split('/').last;
    rows.add([
      fm['incident_id'] ?? '??????',
      fm['detected_at']?.substring(0, 10) ?? '????-??-??',
      fm['status'] ?? '?',
      fm['blast_radius'] ?? '?',
      fm['impact_summary'] ?? '(no summary)',
      '[$filename]($filename)',
    ]);
  }

  final buf = StringBuffer();
  buf.writeln('# Incident Index');
  buf.writeln();
  buf.writeln('Auto-generated by `scripts/build_incident_index.dart`. '
      'Do not edit by hand.');
  buf.writeln();
  buf.writeln('Total: ${rows.length} incident(s).');
  buf.writeln();

  if (rows.isEmpty) {
    buf.writeln('No production incidents recorded yet. This is the '
        'post-paying-user era; the alert detection infra shipped '
        '2026-05-28 (Phase 1 of the incident playbook) and Phase 2 '
        'threshold tuning is scheduled for 2026-06-03.');
    buf.writeln();
    buf.writeln('See [_template.md](_template.md) for the incident '
        'frontmatter contract, and '
        '`.claude/skills/incident/SKILL.md` for `/incident` scaffolding '
        'behavior.');
  } else {
    buf.writeln(
        '| ID | Detected | Status | Blast radius | Impact | File |');
    buf.writeln('|---|---|---|---|---|---|');
    for (final r in rows) {
      buf.writeln('| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3]} | ${r[4]} | ${r[5]} |');
    }
  }

  File('docs/incidents/INDEX.md').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote docs/incidents/INDEX.md (${rows.length} entries).');
}

Map<String, String>? _parseFrontmatter(String content) {
  if (!content.startsWith('---\n')) return null;
  final end = content.indexOf('\n---\n', 4);
  if (end == -1) return null;
  final block = content.substring(4, end);
  final fm = <String, String>{};
  for (final line in block.split('\n')) {
    final m = RegExp(r'^([a-z_]+)\s*:\s*(.+)$').firstMatch(line);
    if (m != null) fm[m.group(1)!] = m.group(2)!.trim();
  }
  return fm;
}
