// Builds docs/handbook/INDEX.md from the categorized handbook tree.
//
// Walks docs/handbook/<category>/*.md, parses frontmatter,
// groups by category, writes a Markdown table per category.
//
// Usage:
//   dart run scripts/build_handbook_index.dart

import 'dart:io';

const _categories = <String>[
  'bug-classes',
  'process',
  'conventions',
  'audit',
  'testing',
];

void main() {
  final root = Directory('docs/handbook');
  if (!root.existsSync()) {
    stderr.writeln('docs/handbook/ does not exist');
    exit(1);
  }

  final buf = StringBuffer();
  buf.writeln('# Handbook Index');
  buf.writeln();
  buf.writeln('Auto-generated by `scripts/build_handbook_index.dart`. '
      'Do not edit by hand.');
  buf.writeln();

  var totalCount = 0;

  for (final category in _categories) {
    final catDir = Directory('docs/handbook/$category');
    if (!catDir.existsSync()) continue;
    final files = catDir
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.md'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

    if (files.isEmpty) continue;

    buf.writeln('## ${_humanize(category)}');
    buf.writeln();
    buf.writeln('| Title | Source memory | Last reviewed |');
    buf.writeln('|---|---|---|');

    for (final f in files) {
      final content = f.readAsStringSync().replaceAll('\r\n', '\n');
      final fm = _parseFrontmatter(content);
      final filename = f.path.replaceAll('\\', '/').split('/').last;
      final title = fm?['title'] ?? '(no title)';
      final source = fm?['source_memory'] ?? '—';
      final reviewed = fm?['last_reviewed'] ?? '—';
      final relPath = '$category/$filename';
      buf.writeln('| [$title]($relPath) | `$source` | $reviewed |');
      totalCount++;
    }
    buf.writeln();
  }

  buf.writeln('---');
  buf.writeln();
  buf.writeln('Total: $totalCount entries.');
  buf.writeln();
  buf.writeln('See [README.md](README.md) for the handbook convention.');

  File('docs/handbook/INDEX.md').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote docs/handbook/INDEX.md ($totalCount entries).');
}

String _humanize(String slug) {
  return slug
      .split('-')
      .map((s) => s.isEmpty ? s : '${s[0].toUpperCase()}${s.substring(1)}')
      .join(' ');
}

Map<String, String>? _parseFrontmatter(String content) {
  if (!content.startsWith('---\n')) return null;
  final end = content.indexOf('\n---\n', 4);
  if (end == -1) return null;
  final block = content.substring(4, end);
  final fm = <String, String>{};
  for (final line in block.split('\n')) {
    final m = RegExp(r'^([a-z_]+)\s*:\s*(.+)$').firstMatch(line);
    if (m != null) fm[m.group(1)!] = m.group(2)!.trim();
  }
  return fm;
}
