-- ============================================================
-- Migration 014: Add Warm-up & Cool-down Exercises
-- 13 warmup + 8 cooldown = 21 new exercises
-- ============================================================

-- WARMUP EXERCISES (13)

INSERT INTO exercise_library (name, category, movement_pattern, exercise_type, primary_muscles, equipment_needed, logging_type, difficulty_level, suitable_for, coaching_cues, common_mistakes, default_sets, default_reps, default_rest_secs, source, is_active)
VALUES
  ('Spot Jogging', 'warmup', 'cardio', 'cardio', ARRAY['Full Body'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Land softly on the balls of your feet; keep knees slightly bent; pump arms naturally'], ARRAY['Landing flat-footed; holding breath; hunching shoulders'], 1, '300s', 0, 'system', true),
  ('Jumping Jacks', 'warmup', 'cardio', 'cardio', ARRAY['Full Body'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Jump feet wide as arms go overhead; land softly; keep a steady rhythm'], ARRAY['Not fully extending arms; landing with locked knees'], 1, '300s', 0, 'system', true),
  ('High Knees', 'warmup', 'cardio', 'cardio', ARRAY['Hip Flexors','Quads'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Drive knees to hip height; pump arms opposite to legs; stay on balls of feet'], ARRAY['Leaning back; knees not reaching hip height; flat-footed landing'], 1, '60s', 0, 'system', true),
  ('Butt Kicks', 'warmup', 'cardio', 'cardio', ARRAY['Hamstrings'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Kick heels towards glutes; keep torso upright; pump arms naturally'], ARRAY['Leaning forward; not reaching glutes; going too slow'], 1, '60s', 0, 'system', true),
  ('Arm Circles', 'warmup', 'rotation', 'dynamic_stretch', ARRAY['Shoulders'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Start with small circles, gradually increase size; do 30s forward then 30s backward; keep arms straight'], ARRAY['Moving too fast; bending elbows; only doing one direction'], 1, '60s', 0, 'system', true),
  ('Neck Rotations', 'warmup', 'rotation', 'dynamic_stretch', ARRAY['Neck'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Slow, controlled circles; do both clockwise and counter-clockwise; keep shoulders relaxed'], ARRAY['Moving too fast; jerky movements; tensing shoulders'], 1, '30s', 0, 'system', true),
  ('Torso Twists', 'warmup', 'rotation', 'dynamic_stretch', ARRAY['Core'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Stand feet shoulder-width; arms at chest level; rotate from the waist, not hips; look in the direction you twist'], ARRAY['Moving hips instead of torso; going too fast; not engaging core'], 1, '60s', 0, 'system', true),
  ('Hip Circles', 'warmup', 'rotation', 'dynamic_stretch', ARRAY['Hip Flexors'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Hands on hips; make large circles with your hips; do both directions; keep upper body still'], ARRAY['Circles too small; only doing one direction; bending knees'], 1, '60s', 0, 'system', true),
  ('Leg Swings', 'warmup', 'dynamic', 'dynamic_stretch', ARRAY['Hip Flexors','Hamstrings'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Hold a wall for balance; swing one leg forward and back; do front-to-back then side-to-side; keep standing leg slightly bent'], ARRAY['Swinging too aggressively; losing balance; rounding the back'], 1, '60s', 0, 'system', true),
  ('Wrist Rotations', 'warmup', 'rotation', 'dynamic_stretch', ARRAY['Forearms'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Interlace fingers and rotate wrists in circles; do both directions; gentle and controlled'], ARRAY['Moving too fast; skipping this before heavy gripping exercises'], 1, '30s', 0, 'system', true),
  ('Ankle Rotations', 'warmup', 'rotation', 'dynamic_stretch', ARRAY['Calves'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Lift one foot; rotate ankle clockwise then counter-clockwise; switch feet'], ARRAY['Skipping this; not doing both directions'], 1, '30s', 0, 'system', true),
  ('Wall Push Up', 'warmup', 'horizontal_push', 'activation', ARRAY['Chest'], ARRAY['Bodyweight'], 'bodyweight_reps', 'beginner', ARRAY['Beginner'], ARRAY['Stand arm''s length from wall; place hands shoulder-width on wall; lower chest towards wall; push back'], ARRAY['Standing too close; flaring elbows; not engaging core'], 1, '10', 0, 'system', true),
  ('Dead Hang', 'warmup', 'static', 'activation', ARRAY['Lats','Forearms'], ARRAY['Pull-Up Bar'], 'timed', 'intermediate', ARRAY['Intermediate','Advanced'], ARRAY['Grip bar shoulder-width; let body hang fully; relax shoulders down; engage core slightly'], ARRAY['Shrugging shoulders up; holding breath; swinging'], 1, '30s', 0, 'system', true);

-- COOLDOWN EXERCISES (8)

INSERT INTO exercise_library (name, category, movement_pattern, exercise_type, primary_muscles, equipment_needed, logging_type, difficulty_level, suitable_for, coaching_cues, common_mistakes, default_sets, default_reps, default_rest_secs, source, is_active)
VALUES
  ('Slow Walking', 'cooldown', 'cardio', 'cardio', ARRAY['Full Body'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Walk at a relaxed pace; let heart rate come down gradually; shake out arms gently'], ARRAY['Stopping suddenly after intense exercise; sitting down immediately'], 1, '300s', 0, 'system', true),
  ('Standing Toe Touch', 'cooldown', 'static', 'static_stretch', ARRAY['Hamstrings'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Stand with feet together; bend forward from hips; reach for toes; keep knees slightly bent if needed'], ARRAY['Bouncing; rounding upper back excessively; locking knees'], 1, '30s', 0, 'system', true),
  ('Standing Quad Stretch', 'cooldown', 'static', 'static_stretch', ARRAY['Quads'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Stand on one leg; grab opposite foot behind you; pull heel to glute; keep knees together; hold a wall for balance'], ARRAY['Arching lower back; knee pointing outward; not holding long enough'], 1, '30s', 0, 'system', true),
  ('Overhead Stretch', 'cooldown', 'static', 'static_stretch', ARRAY['Shoulders'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Interlace fingers; push palms to ceiling; stretch tall; lean gently to each side'], ARRAY['Not fully extending arms; holding breath; arching lower back'], 1, '30s', 0, 'system', true),
  ('Side Bend Stretch', 'cooldown', 'static', 'static_stretch', ARRAY['Obliques'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Stand tall; raise one arm overhead; lean to the opposite side; hold 15s each side'], ARRAY['Leaning forward instead of sideways; not holding long enough'], 1, '30s', 0, 'system', true),
  ('Cross-body Shoulder Stretch', 'cooldown', 'static', 'static_stretch', ARRAY['Rear Deltoid'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Bring one arm across your chest; use opposite hand to press above the elbow; hold 15s each arm'], ARRAY['Pressing on the elbow joint; shrugging the shoulder; rotating the torso'], 1, '30s', 0, 'system', true),
  ('Chest Doorway Stretch', 'cooldown', 'static', 'static_stretch', ARRAY['Chest'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Place forearm on a doorframe or wall at 90 degrees; step forward until you feel the chest stretch; hold 15s each side'], ARRAY['Arm too high or too low; arching the lower back; not holding long enough'], 1, '30s', 0, 'system', true),
  ('Deep Breathing', 'cooldown', 'static', 'recovery', ARRAY['Core'], ARRAY['Bodyweight'], 'timed', 'beginner', ARRAY['Beginner','Intermediate','Advanced'], ARRAY['Stand or sit comfortably; place one hand on chest, one on belly; belly should rise on inhale; slow controlled exhales'], ARRAY['Shallow chest breathing; rushing the exhale; not relaxing shoulders'], 1, '60s', 0, 'system', true);
