// APK Test #12.7 — pin that AI coach interactions sync converts the
// Hive `coach_<timestamp>` key into a deterministic v5 UUID before
// upserting into `ai_coach_interactions`.
//
// Pre-fix: `_syncCoachInteractions` used `'id': entry['id'] ?? key` —
// the Hive key (`coach_999852984`) bypassed any UUID conversion, and
// Postgres rejected with `22P02 invalid input syntax for type uuid:
// "coach_999852984"` on every legacy entry.
//
// Fix: structurally-valid UUIDs (e.g. server-generated by ai-proxy)
// pass through; otherwise we hash via the existing `_deterministicId`
// (sync namespace v5).

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:uuid/uuid.dart';

String _src(String relativePath) {
  final file = File('${Directory.current.path}/$relativePath');
  return file.readAsStringSync();
}

void main() {
  group('Test #12.7 — coach interaction UUID format', () {
    test(
      '_syncCoachInteractions does NOT pass `entry["id"] ?? key` directly to upsert',
      () {
        final src = _src('lib/core/services/sync_service.dart');

        final mIdx = src.indexOf('Future<void> _syncCoachInteractions(');
        expect(mIdx, greaterThan(0));
        final mEnd = src.indexOf('\n  /// ', mIdx + 10);
        final body = src.substring(mIdx,
            mEnd > mIdx ? mEnd : (mIdx + 3000).clamp(0, src.length));

        // The legacy buggy line was `'id': entry['id'] ?? key,` — this
        // exact pattern must NOT survive. The replacement uses a
        // distinct cloudId variable so the upsert receives a valid UUID.
        expect(
          body.contains("'id': entry['id'] ?? key,"),
          isFalse,
          reason: 'Hive key "coach_<timestamp>" is not a valid UUID; '
              'passing it to ai_coach_interactions.id triggers Postgres '
              '22P02. The upsert must hash through _deterministicId.',
        );

        // The fix uses the deterministic UUID generator.
        expect(
          body,
          contains('_deterministicId('),
          reason: '_syncCoachInteractions must build the cloud id with '
              '_deterministicId(...) (v5 with sync namespace) when the '
              'Hive key is not already UUID-shaped.',
        );
      },
    );

    test(
      '_looksLikeUuid helper exists and accepts only structurally-valid uuids',
      () {
        // We can't directly call the private helper from the singleton,
        // but the structural shape (UUID v5 of `coach|userId|key`) is
        // verifiable by reproducing the contract here: the v5 UUID
        // generator from `package:uuid` produces a 36-char canonical
        // form; the Hive key does not. Any output from _deterministicId
        // (which uses the same generator) will satisfy the UUID regex.
        const namespace = '6ba7b810-9dad-11d1-80b4-00c04fd430c8';
        const uuid = Uuid();
        final out =
            uuid.v5(namespace, 'coach|test-user-id|coach_999852984');
        // Canonical UUID regex.
        expect(
          RegExp(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
              .hasMatch(out),
          isTrue,
          reason: 'The helper produces canonical-form UUIDs that '
              'PostgreSQL accepts for the uuid column type.',
        );
        // The raw Hive key fails the same regex — confirming the
        // pre-fix code was sending an invalid value.
        expect(
          RegExp(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
              .hasMatch('coach_999852984'),
          isFalse,
        );
      },
    );
  });
}
